import '@/shared/assets/styles/main.scss';
import { Header } from '@/widgets';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Cat Pinterst',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
