import '@/shared/assets/styles/main.scss';
import { CatListProvider, FavoritesProvider } from '@/features';
import { Header } from '@/widgets';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Cat Pinterst',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <FavoritesProvider>
          <CatListProvider>
            <Header />
            <main>{children}</main>
          </CatListProvider>
        </FavoritesProvider>
      </body>
    </html>
  );
}
